<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1xLvpHF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1xLvpHF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1xLvpHF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1xLvpHF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1xLvpHF\App_KernelDevDebugContainer([
    'container.build_hash' => '1xLvpHF',
    'container.build_id' => 'aada692b',
    'container.build_time' => 1647957564,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1xLvpHF');
