<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], [], []],
    'app_cinema' => [[], ['_controller' => 'App\\Controller\\CinemaController::index'], [], [['text', '/cinema']], [], [], []],
    'app_cinema_liste_realisateurs' => [[], ['_controller' => 'App\\Controller\\CinemaController::cinema_list_realisateur'], [], [['text', '/cinema/realisateurs']], [], [], []],
    'app_cinema_realisateur' => [['id'], ['_controller' => 'App\\Controller\\CinemaController::cinema_realisateur'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cinema']], [], [], []],
    'app_film' => [[], ['_controller' => 'App\\Controller\\FilmController::index'], [], [['text', '/admin/film']], [], [], []],
    'app_film_update' => [['id'], ['_controller' => 'App\\Controller\\FilmController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/film_update']], [], [], []],
    'app_film_delete' => [['id'], ['_controller' => 'App\\Controller\\FilmController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/film_delete']], [], [], []],
    'app_genre' => [[], ['_controller' => 'App\\Controller\\GenreController::index'], [], [['text', '/admin/genre']], [], [], []],
    'app_genre_update' => [['id'], ['_controller' => 'App\\Controller\\GenreController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/genre_update']], [], [], []],
    'app_genre_delete' => [['id'], ['_controller' => 'App\\Controller\\GenreController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/genre_delete']], [], [], []],
    'app_index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'app_realisateur' => [[], ['_controller' => 'App\\Controller\\RealisateurController::index'], [], [['text', '/admin/realisateur']], [], [], []],
    'app_realisateur_update' => [['id'], ['_controller' => 'App\\Controller\\RealisateurController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/realisateur_update']], [], [], []],
    'app_realisateur_delete' => [['id'], ['_controller' => 'App\\Controller\\RealisateurController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/realisateur_delete']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
